files:
  - source: /OmniKitUI/Resources/Localizable.xcstrings
    translation: /OmniKitUI/Resources/Localizable.xcstrings
    multilingual: 1
  - source: /Localizable.xcstrings
    translation: /Localizable.xcstrings
    multilingual: 1
